gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  
paginate: 6
permalink: /:title/

authors:
  maltes:
    name: Maltes
    bio: Parrafo con descripción breve de la raza y posible ficha técnica.
